# kate: indent-width 2;

version: '{branch}-{build}'

branches:
  only:
  - compatibility
skip_tags: true
shallow_clone: true
clone_depth: 1

environment:
  matrix:
  - BUILD_STATIC: OFF

install:
- call "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/vcvarsall.bat"
- set PATH=C:/Sys/bin;C:/tools/ninja;%PATH%

# Ninja
- cinst ninja

build_script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/Sys -DBUILD_STATIC=%BUILD_STATIC% -DBUILD_TESTS=ON -G Ninja
- cmake --build .
- cmake --build . --target install
- cmake . -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/Deploy -DBUILD_TESTS=OFF
- cmake --build . --target install
- cd ../Deploy
- 7z a ../corrade-compatibility.zip *

test_script:
- cd %APPVEYOR_BUILD_FOLDER%/build
- SET fail=0
- ctest --output-on-failure || SET fail=1 & ver > nul
- cd %APPVEYOR_BUILD_FOLDER%
- appveyor PushArtifact corrade-compatibility.zip
- exit %fail%
